In [2]:
import numpy as np
#data types in python


# integer
# Floating
# boolean 
# complexx numbers 
# string
# object 

In [4]:
#complex number
arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])
print(arr1 + arr2)
print(arr1, arr1.dtype)


[5.+8.j]
[3.+5.j] complex128


In [ ]:
#1D array -> 1 axis -> (axis 0)
#2D array -> 2 axes -> (axis 0 (rows)(vertically), axis 1(columns)(horizontally))

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

#sum of ith elements of each row
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

#sum of ith elements of each column
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [10]:
#indexing on 2D arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2D)
print(arr2D[0:2,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5]


In [14]:
#3D array

arr3D = np.array([[[1,2],[3,4], [5,6]], [[7,8], [9, 10], [11, 12]]]) #2 x 3 x 2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])

#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first column from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [4]:
#normalization

arr = np.array([[1,2], [3,4]])

mean = np.mean(arr)

std_dev = np.std(arr)

normalized_arr = (arr - mean) / std_dev

print(normalized_arr)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [ ]:
#aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #prints the index of min element
print(np.argmax(arr)) #prints the index of max element

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [9]:
#power func

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 3))





[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [10]:
#log func

arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [12]:
#rounding

arr = np.array([1,4,2,2,3,4,5])

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))

print(np.trunc(3.14)) #used to truncate values after decimal

print(np.unique(arr))

print(np.sort(arr))

print(np.abs(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 2 2 3 4 4 5]
[1 4 2 2 3 4 5]
