In [1]:
import numpy as np

In [2]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.shape)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [11]:
#create 
arr1 = np.zeros((2,3), dtype="int64") # prefill with zero
print(arr1, arr1.shape)

arr2 = np.ones((5,)) #prefill with one
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefil with val
print(arr3, arr3.shape)

arr4 = np.eye(4) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 11) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #evenly spaced arrays
print(arr6, arr6.shape)



[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


In [12]:
#properties
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape) #prints the dimensions
print(arr.size)
print(arr.dtype)
print(arr.ndim)

#create a new array from the existing array
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)



(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [ ]:
#reshaping mxn array -> nxm array

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [ ]:
#indexing on 1 D
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

#indexing on 2 D
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1[0,2])

1
4
3


In [16]:
#fancy indexing
arr = np.array([1,2,3,4,5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [17]:
#boolean indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [ ]:
#slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]


In [ ]:
#copy vs view
#copy is created in normal list
# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)

# sub_list[0] = 200
# print(sub_list)
# print(nums)

#views is created for numpy arrays
arr = np.array([1,2,3,4,5])

sub_arr = arr[1:3]

print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)




[2 3]
[200   3]
[  1 200   3   4   5]
