In [5]:
import numpy as np
#data types in python


# integer
# Floating
# boolean 
# complexx numbers 
# string
# object 

In [4]:
#complex number
arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])
print(arr1 + arr2)
print(arr1, arr1.dtype)


[5.+8.j]
[3.+5.j] complex128


In [ ]:
#1D array -> 1 axis -> (axis 0)
#2D array -> 2 axes -> (axis 0 (rows)(vertically), axis 1(columns)(horizontally))

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

#sum of ith elements of each row
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

#sum of ith elements of each column
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [10]:
#indexing on 2D arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2D)
print(arr2D[0:2,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5]


In [14]:
#3D array

arr3D = np.array([[[1,2],[3,4], [5,6]], [[7,8], [9, 10], [11, 12]]]) #2 x 3 x 2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])

#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first column from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
